<Project>
  <PropertyGroup>
    <_CoreLibAssemblyName>System.Private.CoreLib.dll</_CoreLibAssemblyName>
    <_PatchedCoreLibDir>$(ArtifactsPath)\patches\$(MSBuildProjectName)</_PatchedCoreLibDir>
    <_PatchedCoreLibPath>$(_PatchedCoreLibDir)\$(_CoreLibAssemblyName)</_PatchedCoreLibPath>
  </PropertyGroup>

  <Target Name="_CollectCoreLibCandidate">
    <ItemGroup>
      <_CoreLibCandidate Remove="@(_CoreLibCandidate)" />
      <_CoreLibCandidate Include="@(ReferenceCopyLocalPaths)"
                         Condition="'%(ReferenceCopyLocalPaths.FileName)%(ReferenceCopyLocalPaths.Extension)' == '$(_CoreLibAssemblyName)'" />
    </ItemGroup>
  </Target>

  <Target Name="PatchCoreLibFile"
          DependsOnTargets="_CollectCoreLibCandidate"
          Condition="'@(ReferenceCopyLocalPaths->WithMetadataValue('FileName','System.Private.CoreLib')->WithMetadataValue('Extension','.dll'))' != ''"
          Inputs="@(_CoreLibCandidate);$(MSBuildThisFileDirectory)patch-corelib.cs"
          Outputs="$(_PatchedCoreLibPath)">

    <MakeDir Directories="$(_PatchedCoreLibDir)" />

    <Exec Command="&quot;$(DOTNET_HOST_PATH)&quot; run --file &quot;$(MSBuildThisFileDirectory)patch-corelib.cs&quot; &quot;@(_CoreLibCandidate)&quot; &quot;$(_PatchedCoreLibPath)&quot;" />
  </Target>

  <Target Name="UsePatchedCoreLib"
          AfterTargets="ResolveReferences"
          BeforeTargets="_ComputeWasmBuildCandidates;_ResolveWasmOutputs"
          DependsOnTargets="PatchCoreLibFile">

    <ItemGroup Condition="'@(_CoreLibCandidate)' != '' and Exists('$(_PatchedCoreLibPath)')">
      <ReferenceCopyLocalPaths Remove="@(_CoreLibCandidate)" />
    </ItemGroup>

    <!-- Use `->` to ensure the original metadata are preserved (only the path is replaced). -->
    <ItemGroup Condition="'@(_CoreLibCandidate)' != '' and Exists('$(_PatchedCoreLibPath)')">
      <ReferenceCopyLocalPaths Include="@(_CoreLibCandidate->'$(_PatchedCoreLibPath)')" KeepDuplicates="false" />
    </ItemGroup>
  </Target>

  <Target Name="PublishPatchedCoreLib"
          AfterTargets="_ResolveCopyLocalAssetsForPublish"
          DependsOnTargets="_CollectCoreLibCandidate;PatchCoreLibFile">
    <ItemGroup Condition="'@(_CoreLibCandidate)' != '' and Exists('$(_PatchedCoreLibPath)')">
      <_ResolvedCopyLocalPublishAssets Remove="@(_CoreLibCandidate)" />
    </ItemGroup>

    <!-- Use `->` to ensure the original metadata are preserved (only the path is replaced). -->
    <ItemGroup Condition="'@(_CoreLibCandidate)' != '' and Exists('$(_PatchedCoreLibPath)')">
      <_ResolvedCopyLocalPublishAssets Include="@(_CoreLibCandidate->'$(_PatchedCoreLibPath)')" KeepDuplicates="false" />
    </ItemGroup>
  </Target>
</Project>
