using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DotNetLab;

[Generator(LanguageNames.CSharp)]
public sealed class NotifyPropertyChangedGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        const string attributeNamespace = "DotNetLab";
        const string attributeName = "OnPropertyChangedAttribute";

        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource($"{attributeName}.g.cs", $$"""
                // <auto-generated/>

                #nullable enable

                namespace {{attributeNamespace}};

                [System.AttributeUsage(System.AttributeTargets.Property, Inherited = false, AllowMultiple = false)]
                internal sealed class {{attributeName}} : System.Attribute;
                """);
        });

        var properties = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: $"{attributeNamespace}.{attributeName}",
            predicate: static (node, ct) => node is PropertyDeclarationSyntax,
            transform: static (context, ct) =>
            {
                var propertySymbol = (IPropertySymbol)context.TargetSymbol;
                var containingTypeSymbol = propertySymbol.ContainingType;
                var typeModel = new TypeModel(
                    Namespace: containingTypeSymbol.ContainingNamespace?.ToDisplayString(),
                    TypeName: containingTypeSymbol.Name,
                    IsSealed: containingTypeSymbol.IsSealed);
                return new PropertyModel(
                    ContainingType: typeModel,
                    PropertyType: propertySymbol.Type.ToDisplayString(),
                    Name: propertySymbol.Name,
                    Accessibility: SyntaxFacts.GetText(propertySymbol.DeclaredAccessibility));
            });

        context.RegisterSourceOutput(properties, static (ctx, property) =>
        {
            var type = property.ContainingType;
            ctx.AddSource($"{(type.Namespace is null ? "" : $"{type.Namespace}.")}{type.TypeName}.{property.Name}.g.cs", $$"""
                // <auto-generated/>

                #nullable enable

                {{(type.Namespace is null ? "" : $"namespace {type.Namespace};")}}

                partial class {{type.TypeName}}
                {
                    {{property.Accessibility}} partial {{property.PropertyType}} {{property.Name}}
                    {
                        get => field;
                        set
                        {
                            if (!System.Collections.Generic.EqualityComparer<{{property.PropertyType}}>.Default.Equals(value, field))
                            {
                                field = value;
                                OnPropertyChanged(nameof({{property.Name}}));
                            }
                        }
                    }
                }
                """);
        });
    }

    private sealed record TypeModel(
        string? Namespace,
        string TypeName,
        bool IsSealed);

    private sealed record PropertyModel(
        TypeModel ContainingType,
        string PropertyType,
        string Name,
        string Accessibility);
}
